-- Generated by seed/make.py: Wyatt, his collection, and the current site's grid puzzles as sketches.
INSERT OR IGNORE INTO creators (id, name, email, handle) VALUES ('wyatt', 'Wyatt', 'wyatt@example.invalid', 'wyatt');
INSERT OR IGNORE INTO collections (id, slug, title, description, personal_of) VALUES ('c-wyatt', 'wyatt', 'Wyatt''s Games', 'Puzzles Wyatt drew.', 'wyatt');
INSERT OR IGNORE INTO memberships (collection_id, creator_id, role) VALUES ('c-wyatt', 'wyatt', 'owner');
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('river-1', 'c-wyatt', 'wyatt', 'Little Pond', 'river
{
 "size": [
  3,
  3
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "block"
  }
 ]
}', 'river', 'published', (unixepoch() * 1000) + 1);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('river-2', 'c-wyatt', 'wyatt', 'Stepping Stones', 'river
{
 "size": [
  4,
  4
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    2,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "block"
  }
 ]
}', 'river', 'published', (unixepoch() * 1000) + 2);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('river-3', 'c-wyatt', 'wyatt', 'Canyon Run', 'river
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    5,
    0
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     0,
     1
    ],
    [
     1,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     0
    ],
    [
     1,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     4
    ],
    [
     1,
     5
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     4
    ],
    [
     2,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     3,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     2
    ],
    [
     2,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     3
    ],
    [
     3,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     4
    ],
    [
     4,
     4
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'river', 'published', (unixepoch() * 1000) + 3);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('river-4', 'c-wyatt', 'wyatt', 'Long Bend', 'river
{
 "size": [
  6,
  7
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    1,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    5
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     0,
     4
    ],
    [
     1,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     3
    ],
    [
     1,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     2
    ],
    [
     2,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     3
    ],
    [
     3,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     5
    ],
    [
     3,
     6
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     3,
     1
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'river', 'published', (unixepoch() * 1000) + 4);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('river-5', 'c-wyatt', 'wyatt', 'Twin Peaks', 'river
{
 "size": [
  5,
  5
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     0
    ],
    [
     1,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     3
    ],
    [
     1,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     1
    ],
    [
     3,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     2
    ],
    [
     4,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     2
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'river', 'published', (unixepoch() * 1000) + 5);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('river-6', 'c-wyatt', 'wyatt', 'Narrow Pass', 'river
{
 "size": [
  5,
  4
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    0
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     2
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'river', 'published', (unixepoch() * 1000) + 6);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('river-7', 'c-wyatt', 'wyatt', 'Little Loop', 'river
{
 "size": [
  4,
  4
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    1,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    3
   ],
   "kind": "block"
  }
 ]
}', 'river', 'published', (unixepoch() * 1000) + 7);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('river-8', 'c-wyatt', 'wyatt', 'Six Rows Down', 'river
{
 "size": [
  6,
  5
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    5,
    4
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     2
    ],
    [
     1,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     3,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     2
    ],
    [
     3,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     4,
     0
    ],
    [
     4,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'river', 'published', (unixepoch() * 1000) + 8);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-1', 'c-wyatt', 'wyatt', 'Something Sweet', 'nonogram
{
 "size": [
  5,
  5
 ],
 "picture": {
  "rows": [
   ".r.r.",
   "rrrrr",
   "rrrrr",
   ".rrr.",
   "..r.."
  ],
  "palette": {
   ".": "#e3f2f6",
   "r": "#d8443a"
  },
  "title": "Heart"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 9);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-2', 'c-wyatt', 'wyatt', 'From the Tree', 'nonogram
{
 "size": [
  10,
  10
 ],
 "picture": {
  "rows": [
   ".....b....",
   "....bgg...",
   "..rrbrrr..",
   ".rrrrrrhr.",
   "rrrrrrrrhr",
   "rrrrrrrrrr",
   "rrrrrrrrrr",
   ".rrrrrrrr.",
   ".rrrrrrrr.",
   "..rr..rr.."
  ],
  "palette": {
   ".": "#e3f2f6",
   "r": "#d8443a",
   "h": "#f29a8c",
   "b": "#6b4a2b",
   "g": "#4a9a3b"
  },
  "title": "Apple"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 10);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-3', 'c-wyatt', 'wyatt', 'Out on the Water', 'nonogram
{
 "size": [
  10,
  10
 ],
 "picture": {
  "rows": [
   "....w.....",
   "....ww....",
   "....www...",
   "....wwww..",
   "....wwwww.",
   "....m.....",
   ".bbbbbbbb.",
   "..bbbbbb..",
   "~~~~~~~~~~",
   ".~~.~~.~~."
  ],
  "palette": {
   ".": "#e3f2f6",
   "w": "#ffffff",
   "m": "#6b4a2b",
   "b": "#a0662f",
   "~": "#2f8fd8"
  },
  "title": "Sailboat"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 11);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-4', 'c-wyatt', 'wyatt', 'In the Forest', 'nonogram
{
 "size": [
  10,
  10
 ],
 "picture": {
  "rows": [
   "..rrrrrr..",
   ".rrwwrrrr.",
   "rrwwrrrwwr",
   "rrrrrrrwwr",
   "rwwrrrrrrr",
   "..cccccc..",
   "...cccc...",
   "...cccc...",
   "...cccc...",
   "..cccccc.."
  ],
  "palette": {
   ".": "#e8f1dc",
   "r": "#d8443a",
   "w": "#fff6e8",
   "c": "#e9dcc0"
  },
  "title": "Mushroom"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 12);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-5', 'c-wyatt', 'wyatt', 'Sitting Pretty', 'nonogram
{
 "size": [
  10,
  10
 ],
 "picture": {
  "rows": [
   "k...k.....",
   "kk.kk.....",
   "kkkkk.....",
   "kekek.....",
   "kkkkk...k.",
   ".kkk....k.",
   ".kkkkkkkk.",
   ".kkkkkkk..",
   ".k.k..k.k.",
   ".k.k..k.k."
  ],
  "palette": {
   ".": "#fbeed7",
   "k": "#3b3633",
   "e": "#f2c94c"
  },
  "title": "Cat"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 13);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-6', 'c-wyatt', 'wyatt', 'Tall Word', 'nonogram
{
 "size": [
  15,
  3
 ],
 "picture": {
  "rows": [
   "ppp",
   "p.p",
   "ppp",
   "p..",
   "p..",
   "...",
   "ppp",
   "p.p",
   "ppp",
   "...",
   "ppp",
   "p.p",
   "ppp",
   "p..",
   "p.."
  ],
  "palette": {
   ".": "#fdf1e4",
   "p": "#e2508f"
  },
  "title": "Pop"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 14);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-7', 'c-wyatt', 'wyatt', 'Say My Name', 'nonogram
{
 "size": [
  5,
  12
 ],
 "picture": {
  "rows": [
   "bb..bbbb.bb.",
   "b.b.b..b.b.b",
   "bb..b..b.bb.",
   "b.b.b..b.b.b",
   "bb..bbbb.bb."
  ],
  "palette": {
   ".": "#eef4fb",
   "b": "#2f6fd8"
  },
  "title": "Bob"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 15);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-8', 'c-wyatt', 'wyatt', 'First Place', 'nonogram
{
 "size": [
  10,
  7
 ],
 "picture": {
  "rows": [
   ".ttttt.",
   "t.....t",
   ".......",
   "t.ttt.t",
   "t.ttt.t",
   "t.....t",
   "ttttttt",
   ".......",
   "..ttt..",
   "..ttt.."
  ],
  "palette": {
   ".": "#eef4fb",
   "t": "#e0a422"
  },
  "title": "Trophy"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 16);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-9', 'c-wyatt', 'wyatt', 'Standing Tall', 'nonogram
{
 "size": [
  8,
  4
 ],
 "picture": {
  "rows": [
   ".ss.",
   "rrrr",
   ".rr.",
   ".rr.",
   "bbbb",
   "b..b",
   "b..b",
   "b..b"
  ],
  "palette": {
   ".": "#f3efe6",
   "s": "#e8b48a",
   "r": "#d8443a",
   "b": "#2d58a6"
  },
  "title": "Human"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 17);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('slitherlink-1', 'c-wyatt', 'wyatt', 'First Loop', 'slitherlink
{
 "size": [
  5,
  5
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    2,
    1
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    3,
    4
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    2,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    1
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    0
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "number",
   "value": 2
  }
 ]
}', 'slitherlink', 'published', (unixepoch() * 1000) + 18);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('slitherlink-2', 'c-wyatt', 'wyatt', 'Long Way Round', 'slitherlink
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    1,
    5
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    5
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    4
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    1,
    4
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    4,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    4,
    1
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    4
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 1
  }
 ]
}', 'slitherlink', 'published', (unixepoch() * 1000) + 19);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nurikabe-1', 'c-wyatt', 'wyatt', 'Five Islands', 'nurikabe
{
 "size": [
  5,
  5
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    0,
    4
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 5
  }
 ]
}', 'nurikabe', 'published', (unixepoch() * 1000) + 20);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nurikabe-2', 'c-wyatt', 'wyatt', 'Archipelago', 'nurikabe
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    0,
    4
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    5
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    5,
    4
   ],
   "kind": "number",
   "value": 1
  }
 ]
}', 'nurikabe', 'published', (unixepoch() * 1000) + 21);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('panes-1', 'c-wyatt', 'wyatt', 'Four by Four', 'panes
{
 "size": [
  4,
  4
 ],
 "rules": [
  {
   "rule": "size",
   "is": 4
  },
  {
   "rule": "twins"
  },
  {
   "rule": "opposites"
  }
 ],
 "givens": [
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     2,
     2
    ]
   ],
   "kind": "opposites"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     3,
     1
    ]
   ],
   "kind": "twins"
  },
  {
   "at": "border",
   "cells": [
    [
     0,
     0
    ],
    [
     1,
     0
    ]
   ],
   "kind": "opposites"
  }
 ]
}', 'panes', 'published', (unixepoch() * 1000) + 22);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('panes-2', 'c-wyatt', 'wyatt', 'Compass Rose', 'panes
{
 "size": [
  5,
  5
 ],
 "rules": [
  {
   "rule": "size",
   "is": 5
  },
  {
   "rule": "twins"
  },
  {
   "rule": "compass"
  }
 ],
 "givens": [
  {
   "at": "border",
   "cells": [
    [
     3,
     3
    ],
    [
     4,
     3
    ]
   ],
   "kind": "twins"
  },
  {
   "at": "cell",
   "cell": [
    4,
    4
   ],
   "kind": "compass",
   "value": {
    "n": 0,
    "e": 0,
    "s": 0,
    "w": 4
   }
  },
  {
   "at": "cell",
   "cell": [
    2,
    1
   ],
   "kind": "compass",
   "value": {
    "n": 3,
    "e": 1,
    "s": 0,
    "w": 2
   }
  },
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "compass",
   "value": {
    "n": 0,
    "e": 4,
    "s": 1,
    "w": 0
   }
  }
 ]
}', 'panes', 'published', (unixepoch() * 1000) + 23);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('sudoku-1', 'c-wyatt', 'wyatt', 'Warm-up', 'sudoku
{
 "size": [
  4,
  4
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    3,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    2
   ],
   "kind": "number",
   "value": 1
  }
 ]
}', 'sudoku', 'published', (unixepoch() * 1000) + 24);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('sudoku-2', 'c-wyatt', 'wyatt', 'Six by Six', 'sudoku
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    2,
    4
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    2,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    2
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    5,
    0
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 3
  }
 ]
}', 'sudoku', 'published', (unixepoch() * 1000) + 25);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('sudoku-3', 'c-wyatt', 'wyatt', 'Classic', 'sudoku
{
 "size": [
  9,
  9
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    7,
    2
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    7,
    6
   ],
   "kind": "number",
   "value": 9
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    2,
    4
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    0,
    7
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    8,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    5
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    7,
    5
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    3,
    7
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    2
   ],
   "kind": "number",
   "value": 7
  },
  {
   "at": "cell",
   "cell": [
    0,
    1
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    7,
    4
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    8,
    1
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    1,
    5
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    1,
    6
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    3,
    8
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    4,
    7
   ],
   "kind": "number",
   "value": 9
  },
  {
   "at": "cell",
   "cell": [
    6,
    5
   ],
   "kind": "number",
   "value": 8
  },
  {
   "at": "cell",
   "cell": [
    8,
    7
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    5,
    8
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    7
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    6,
    1
   ],
   "kind": "number",
   "value": 7
  }
 ]
}', 'sudoku', 'published', (unixepoch() * 1000) + 26);
INSERT OR IGNORE INTO featured (game_id, position, featured_by) VALUES ('river-5', 0, 'wyatt'), ('panes-1', 1, 'wyatt'), ('sudoku-1', 2, 'wyatt'), ('nonogram-2', 3, 'wyatt');
