-- Generated by seed/make.py: Wyatt, his collection, and the current site's grid puzzles as sketches.
INSERT OR IGNORE INTO creators (id, name, email, handle) VALUES ('wyatt', 'Wyatt', 'wyatt@example.invalid', 'wyatt');
INSERT OR IGNORE INTO collections (id, slug, title, description, personal_of) VALUES ('c-wyatt', 'wyatt', 'Wyatt''s Games', 'Puzzles Wyatt drew.', 'wyatt');
INSERT OR IGNORE INTO memberships (collection_id, creator_id, role) VALUES ('c-wyatt', 'wyatt', 'owner');
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('maze-1', 'c-wyatt', 'wyatt', 'Warm-up', 'maze
{
 "size": [
  4,
  4
 ],
 "givens": [
  {
   "at": "edge",
   "cell": [
    0,
    3
   ],
   "side": "top",
   "kind": "door",
   "role": "in"
  },
  {
   "at": "edge",
   "cell": [
    2,
    3
   ],
   "side": "right",
   "kind": "door",
   "role": "out"
  },
  {
   "at": "corner",
   "corner": [
    0,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    2
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    0,
    3
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    0,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    4
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    2,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    2,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    3
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    2,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    2
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    3
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    1
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    4,
    2
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    4,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    4
   ],
   "kind": "count",
   "value": 2
  }
 ]
}', 'maze', 'published', (unixepoch() * 1000) + 1);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('maze-2', 'c-wyatt', 'wyatt', 'The Big Maze', 'maze
{
 "size": [
  15,
  10
 ],
 "givens": [
  {
   "at": "edge",
   "cell": [
    0,
    9
   ],
   "side": "top",
   "kind": "door",
   "role": "in"
  },
  {
   "at": "edge",
   "cell": [
    13,
    9
   ],
   "side": "right",
   "kind": "door",
   "role": "out"
  },
  {
   "at": "border",
   "cells": [
    [
     12,
     3
    ],
    [
     12,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     12,
     1
    ],
    [
     13,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     13,
     1
    ],
    [
     13,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "corner",
   "corner": [
    0,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    4
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    0,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    6
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    7
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    8
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    9
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    0,
    10
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    4
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    1,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    6
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    1,
    7
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    9
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    0
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    2,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    2,
    2
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    2,
    3
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    2,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    2,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    6
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    7
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    2,
    8
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    2,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    2
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    3,
    3
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    6
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    3,
    7
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    3,
    8
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    9
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    0
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    4,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    4
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    4,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    7
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    4,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    5,
    2
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    5,
    3
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    5,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    5,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    5,
    6
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    5,
    7
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    5,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    5,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    0
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    6,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    6,
    2
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    6,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    6,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    6
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    7
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    6,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    6,
    9
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    6,
    10
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    7,
    0
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    7,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    7,
    2
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    7,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    4
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    7,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    7,
    7
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    7,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    7,
    9
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    7,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    8,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    8,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    8,
    2
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    8,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    8,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    8,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    8,
    6
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    8,
    7
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    8,
    8
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    8,
    9
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    8,
    10
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    9,
    0
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    9,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    9,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    9,
    3
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    9,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    9,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    9,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    9,
    7
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    9,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    9,
    9
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    9,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    10,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    10,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    10,
    2
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    10,
    3
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    10,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    10,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    10,
    6
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    10,
    7
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    10,
    8
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    10,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    10,
    10
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    11,
    0
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    11,
    1
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    11,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    11,
    3
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    11,
    4
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    11,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    11,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    11,
    7
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    11,
    8
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    11,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    11,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    12,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    12,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    12,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    12,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    12,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    12,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    12,
    6
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    12,
    7
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    12,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    12,
    9
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    12,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    13,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    13,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    13,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    13,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    13,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    13,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    13,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    13,
    7
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    13,
    8
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    13,
    9
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    13,
    10
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    14,
    0
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    14,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    14,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    14,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    14,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    14,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    14,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    14,
    7
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    14,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    14,
    9
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    14,
    10
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    15,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    15,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    15,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    15,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    15,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    15,
    5
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    15,
    6
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    15,
    7
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    15,
    8
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    15,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    15,
    10
   ],
   "kind": "count",
   "value": 2
  }
 ]
}', 'maze', 'published', (unixepoch() * 1000) + 2);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('maze-3', 'c-wyatt', 'wyatt', 'Side Doors', 'maze
{
 "size": [
  7,
  9
 ],
 "givens": [
  {
   "at": "edge",
   "cell": [
    0,
    0
   ],
   "side": "left",
   "kind": "door",
   "role": "in"
  },
  {
   "at": "edge",
   "cell": [
    6,
    0
   ],
   "side": "left",
   "kind": "door",
   "role": "out"
  },
  {
   "at": "corner",
   "corner": [
    0,
    0
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    0,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    6
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    0,
    7
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    8
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    0,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    0
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    2
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    1,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    6
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    1,
    7
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    1,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    0
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    2,
    1
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    2,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    3
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    2,
    4
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    2,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    2,
    7
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    8
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    2,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    2
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    3,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    4
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    3,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    7
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    3,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    3,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    1
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    2
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    4,
    5
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    4,
    6
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    7
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    4,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    4,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    0
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    2
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    5,
    3
   ],
   "kind": "count",
   "value": 4
  },
  {
   "at": "corner",
   "corner": [
    5,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    5
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    5,
    6
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    7
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    5,
    8
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    5,
    9
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    0
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    6,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    2
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    6
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    6,
    7
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    6,
    8
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    6,
    9
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    7,
    0
   ],
   "kind": "count",
   "value": 1
  },
  {
   "at": "corner",
   "corner": [
    7,
    1
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    2
   ],
   "kind": "count",
   "value": 3
  },
  {
   "at": "corner",
   "corner": [
    7,
    3
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    4
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    5
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    6
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    7
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    8
   ],
   "kind": "count",
   "value": 2
  },
  {
   "at": "corner",
   "corner": [
    7,
    9
   ],
   "kind": "count",
   "value": 2
  }
 ]
}', 'maze', 'published', (unixepoch() * 1000) + 3);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('coats-1', 'c-wyatt', 'wyatt', 'Triangle', 'coats
{
 "size": [
  1,
  4
 ],
 "figure": {
  "pieces": [
   [
    [
     5,
     8.66
    ],
    [
     15,
     8.66
    ],
    [
     10,
     17.321
    ]
   ],
   [
    [
     10,
     0
    ],
    [
     15,
     8.66
    ],
    [
     5,
     8.66
    ]
   ],
   [
    [
     5,
     8.66
    ],
    [
     10,
     17.321
    ],
    [
     0,
     17.321
    ]
   ],
   [
    [
     15,
     8.66
    ],
    [
     20,
     17.321
    ],
    [
     10,
     17.321
    ]
   ]
  ]
 },
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "dots",
   "value": [
    1,
    1,
    1
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    1
   ],
   "kind": "dots",
   "value": [
    2
   ],
   "hidden": true
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "dots",
   "value": [
    2
   ],
   "hidden": true
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "dots",
   "value": [
    2
   ],
   "hidden": true
  }
 ]
}', 'coats', 'published', (unixepoch() * 1000) + 4);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('coats-2', 'c-wyatt', 'wyatt', 'Hexagon', 'coats
{
 "size": [
  1,
  7
 ],
 "figure": {
  "pieces": [
   [
    [
     0.0,
     -9.0
    ],
    [
     7.794,
     -4.5
    ],
    [
     7.794,
     4.5
    ],
    [
     0.0,
     9.0
    ],
    [
     -7.794,
     4.5
    ],
    [
     -7.794,
     -4.5
    ]
   ],
   [
    [
     0.0,
     -20.0
    ],
    [
     17.321,
     -10.0
    ],
    [
     7.794,
     -4.5
    ],
    [
     0.0,
     -9.0
    ]
   ],
   [
    [
     17.321,
     -10.0
    ],
    [
     17.321,
     10.0
    ],
    [
     7.794,
     4.5
    ],
    [
     7.794,
     -4.5
    ]
   ],
   [
    [
     17.321,
     10.0
    ],
    [
     0.0,
     20.0
    ],
    [
     0.0,
     9.0
    ],
    [
     7.794,
     4.5
    ]
   ],
   [
    [
     0.0,
     20.0
    ],
    [
     -17.321,
     10.0
    ],
    [
     -7.794,
     4.5
    ],
    [
     0.0,
     9.0
    ]
   ],
   [
    [
     -17.321,
     10.0
    ],
    [
     -17.321,
     -10.0
    ],
    [
     -7.794,
     -4.5
    ],
    [
     -7.794,
     4.5
    ]
   ],
   [
    [
     -17.321,
     -10.0
    ],
    [
     0.0,
     -20.0
    ],
    [
     0.0,
     -9.0
    ],
    [
     -7.794,
     -4.5
    ]
   ]
  ]
 },
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    1
   ],
   "kind": "dots",
   "value": [
    2,
    3
   ],
   "hidden": true
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "dots",
   "value": [
    2,
    2
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "dots",
   "value": [
    3,
    3,
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    4
   ],
   "kind": "dots",
   "value": [
    1
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    5
   ],
   "kind": "dots",
   "value": [
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    6
   ],
   "kind": "dots",
   "value": [
    3
   ],
   "hidden": true
  }
 ]
}', 'coats', 'published', (unixepoch() * 1000) + 5);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('coats-3', 'c-wyatt', 'wyatt', 'Nine Squares', 'coats
{
 "size": [
  1,
  9
 ],
 "figure": {
  "pieces": [
   [
    [
     0,
     0
    ],
    [
     10,
     0
    ],
    [
     10,
     10
    ],
    [
     0,
     10
    ]
   ],
   [
    [
     10,
     0
    ],
    [
     20,
     0
    ],
    [
     20,
     10
    ],
    [
     10,
     10
    ]
   ],
   [
    [
     20,
     0
    ],
    [
     30,
     0
    ],
    [
     30,
     10
    ],
    [
     20,
     10
    ]
   ],
   [
    [
     0,
     10
    ],
    [
     10,
     10
    ],
    [
     10,
     20
    ],
    [
     0,
     20
    ]
   ],
   [
    [
     10,
     10
    ],
    [
     20,
     10
    ],
    [
     20,
     20
    ],
    [
     10,
     20
    ]
   ],
   [
    [
     20,
     10
    ],
    [
     30,
     10
    ],
    [
     30,
     20
    ],
    [
     20,
     20
    ]
   ],
   [
    [
     0,
     20
    ],
    [
     10,
     20
    ],
    [
     10,
     30
    ],
    [
     0,
     30
    ]
   ],
   [
    [
     10,
     20
    ],
    [
     20,
     20
    ],
    [
     20,
     30
    ],
    [
     10,
     30
    ]
   ],
   [
    [
     20,
     20
    ],
    [
     30,
     20
    ],
    [
     30,
     30
    ],
    [
     20,
     30
    ]
   ]
  ]
 },
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    1
   ],
   "kind": "dots",
   "value": [
    3,
    3,
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "dots",
   "value": [
    1,
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    5
   ],
   "kind": "dots",
   "value": [
    1,
    3,
    3
   ],
   "hidden": true
  },
  {
   "at": "cell",
   "cell": [
    0,
    6
   ],
   "kind": "dots",
   "value": [
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    7
   ],
   "kind": "dots",
   "value": [
    2
   ],
   "hidden": true
  },
  {
   "at": "cell",
   "cell": [
    0,
    8
   ],
   "kind": "dots",
   "value": [
    2,
    3
   ]
  }
 ]
}', 'coats', 'published', (unixepoch() * 1000) + 6);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('coats-4', 'c-wyatt', 'wyatt', 'Square in a Kite', 'coats
{
 "size": [
  1,
  3
 ],
 "figure": {
  "pieces": [
   [
    [
     180,
     205
    ],
    [
     405,
     200
    ],
    [
     430.0,
     391.3
    ],
    [
     215,
     400
    ]
   ],
   [
    [
     180,
     205
    ],
    [
     650,
     0
    ],
    [
     735,
     240
    ],
    [
     430.0,
     391.3
    ],
    [
     405,
     200
    ]
   ],
   [
    [
     180,
     205
    ],
    [
     215,
     400
    ],
    [
     430.0,
     391.3
    ],
    [
     100,
     555
    ]
   ]
  ]
 },
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "dots",
   "value": [
    1,
    1
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    1
   ],
   "kind": "dots",
   "value": [
    3
   ]
  }
 ]
}', 'coats', 'published', (unixepoch() * 1000) + 7);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('coats-5', 'c-wyatt', 'wyatt', 'Envelope', 'coats
{
 "size": [
  1,
  8
 ],
 "figure": {
  "pieces": [
   [
    [
     70,
     205
    ],
    [
     230.0,
     54.2
    ],
    [
     310.0,
     129.1
    ],
    [
     425.0,
     236.9
    ],
    [
     492.4,
     300.0
    ],
    [
     230,
     400
    ]
   ],
   [
    [
     310.0,
     129.1
    ],
    [
     375.0,
     57.1
    ],
    [
     509.1,
     155.0
    ],
    [
     425.0,
     236.9
    ]
   ],
   [
    [
     20,
     50
    ],
    [
     230.0,
     54.2
    ],
    [
     70,
     205
    ]
   ],
   [
    [
     70,
     205
    ],
    [
     230,
     400
    ],
    [
     65,
     395
    ]
   ],
   [
    [
     230,
     400
    ],
    [
     492.4,
     300.0
    ],
    [
     470,
     495
    ]
   ],
   [
    [
     230.0,
     54.2
    ],
    [
     375.0,
     57.1
    ],
    [
     310.0,
     129.1
    ]
   ],
   [
    [
     375.0,
     57.1
    ],
    [
     520,
     60
    ],
    [
     509.1,
     155.0
    ]
   ],
   [
    [
     425.0,
     236.9
    ],
    [
     509.1,
     155.0
    ],
    [
     492.4,
     300.0
    ]
   ]
  ]
 },
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "dots",
   "value": [
    1,
    1,
    1,
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    1
   ],
   "kind": "dots",
   "value": [
    1,
    2,
    2,
    2
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    7
   ],
   "kind": "dots",
   "value": [
    1,
    3
   ]
  }
 ]
}', 'coats', 'published', (unixepoch() * 1000) + 8);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('coats-6', 'c-wyatt', 'wyatt', 'House', 'coats
{
 "size": [
  1,
  7
 ],
 "figure": {
  "pieces": [
   [
    [
     290.0,
     65.9
    ],
    [
     452.1,
     195.0
    ],
    [
     330.0,
     352.5
    ],
    [
     180.0,
     215.0
    ]
   ],
   [
    [
     40,
     195
    ],
    [
     160,
     75
    ],
    [
     180.0,
     215.0
    ]
   ],
   [
    [
     40,
     195
    ],
    [
     180.0,
     215.0
    ],
    [
     200,
     355
    ]
   ],
   [
    [
     160,
     75
    ],
    [
     290.0,
     65.9
    ],
    [
     180.0,
     215.0
    ]
   ],
   [
    [
     290.0,
     65.9
    ],
    [
     445,
     55
    ],
    [
     452.1,
     195.0
    ]
   ],
   [
    [
     452.1,
     195.0
    ],
    [
     460,
     350
    ],
    [
     330.0,
     352.5
    ]
   ],
   [
    [
     180.0,
     215.0
    ],
    [
     330.0,
     352.5
    ],
    [
     200,
     355
    ]
   ]
  ]
 },
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "dots",
   "value": [
    3,
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    1
   ],
   "kind": "dots",
   "value": [
    1,
    2
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "dots",
   "value": [
    2
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "dots",
   "value": [
    1,
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    0,
    6
   ],
   "kind": "dots",
   "value": [
    1,
    2
   ]
  }
 ]
}', 'coats', 'published', (unixepoch() * 1000) + 9);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-loop-1', 'c-wyatt', 'wyatt', 'Little Pond', 'simple-loop
{
 "size": [
  3,
  3
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "block"
  }
 ]
}', 'simple-loop', 'published', (unixepoch() * 1000) + 10);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-loop-2', 'c-wyatt', 'wyatt', 'Stepping Stones', 'simple-loop
{
 "size": [
  4,
  4
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    2,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "block"
  }
 ]
}', 'simple-loop', 'published', (unixepoch() * 1000) + 11);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-loop-3', 'c-wyatt', 'wyatt', 'Canyon Run', 'simple-loop
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    5,
    0
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     0,
     1
    ],
    [
     1,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     0
    ],
    [
     1,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     4
    ],
    [
     1,
     5
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     4
    ],
    [
     2,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     3,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     2
    ],
    [
     2,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     3
    ],
    [
     3,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     4
    ],
    [
     4,
     4
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'simple-loop', 'published', (unixepoch() * 1000) + 12);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-loop-4', 'c-wyatt', 'wyatt', 'Long Bend', 'simple-loop
{
 "size": [
  6,
  7
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    1,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    5
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     0,
     4
    ],
    [
     1,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     3
    ],
    [
     1,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     2
    ],
    [
     2,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     3
    ],
    [
     3,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     5
    ],
    [
     3,
     6
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     3,
     1
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'simple-loop', 'published', (unixepoch() * 1000) + 13);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-loop-5', 'c-wyatt', 'wyatt', 'Twin Peaks', 'simple-loop
{
 "size": [
  5,
  5
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     0
    ],
    [
     1,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     3
    ],
    [
     1,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     1
    ],
    [
     3,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     2
    ],
    [
     4,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     2
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'simple-loop', 'published', (unixepoch() * 1000) + 14);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-loop-6', 'c-wyatt', 'wyatt', 'Narrow Pass', 'simple-loop
{
 "size": [
  5,
  4
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    0
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     2
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'simple-loop', 'published', (unixepoch() * 1000) + 15);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-loop-7', 'c-wyatt', 'wyatt', 'Little Loop', 'simple-loop
{
 "size": [
  4,
  4
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    1,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    3
   ],
   "kind": "block"
  }
 ]
}', 'simple-loop', 'published', (unixepoch() * 1000) + 16);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-loop-8', 'c-wyatt', 'wyatt', 'Six Rows Down', 'simple-loop
{
 "size": [
  6,
  5
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    5,
    4
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     2
    ],
    [
     1,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     3,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     2
    ],
    [
     3,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     4,
     0
    ],
    [
     4,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     2,
     2
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'simple-loop', 'published', (unixepoch() * 1000) + 17);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-path-1', 'c-wyatt', 'wyatt', 'First Steps', 'simple-path
{
 "size": [
  5,
  5
 ],
 "givens": [
  {
   "at": "edge",
   "kind": "door",
   "role": "in",
   "side": "bottom",
   "cell": [
    4,
    4
   ]
  },
  {
   "at": "edge",
   "kind": "door",
   "role": "out",
   "side": "right",
   "cell": [
    2,
    4
   ]
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    2,
    1
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     3
    ],
    [
     1,
     4
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'simple-path', 'published', (unixepoch() * 1000) + 18);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-path-2', 'c-wyatt', 'wyatt', 'Around the Rocks', 'simple-path
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "edge",
   "kind": "door",
   "role": "in",
   "side": "left",
   "cell": [
    4,
    0
   ]
  },
  {
   "at": "edge",
   "kind": "door",
   "role": "out",
   "side": "top",
   "cell": [
    0,
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     4,
     4
    ],
    [
     4,
     5
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     2
    ],
    [
     3,
     2
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     3
    ],
    [
     1,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     3
    ],
    [
     3,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     4,
     1
    ],
    [
     5,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     3
    ],
    [
     2,
     3
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'simple-path', 'published', (unixepoch() * 1000) + 19);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('simple-path-3', 'c-wyatt', 'wyatt', 'Long Way Round', 'simple-path
{
 "size": [
  7,
  7
 ],
 "givens": [
  {
   "at": "edge",
   "kind": "door",
   "role": "in",
   "side": "right",
   "cell": [
    4,
    6
   ]
  },
  {
   "at": "edge",
   "kind": "door",
   "role": "out",
   "side": "bottom",
   "cell": [
    6,
    3
   ]
  },
  {
   "at": "cell",
   "cell": [
    6,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    1,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    4
   ],
   "kind": "block"
  },
  {
   "at": "border",
   "cells": [
    [
     4,
     2
    ],
    [
     4,
     3
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     3,
     1
    ],
    [
     4,
     1
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     4
    ],
    [
     2,
     4
    ]
   ],
   "kind": "wall"
  },
  {
   "at": "border",
   "cells": [
    [
     1,
     4
    ],
    [
     1,
     5
    ]
   ],
   "kind": "wall"
  }
 ]
}', 'simple-path', 'published', (unixepoch() * 1000) + 20);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('star-battle-1', 'c-wyatt', 'wyatt', 'First Stars', 'star-battle
{
 "size": [
  5,
  5
 ],
 "areas": [
  "cbbbd",
  "cbddd",
  "cceaa",
  "eeeea",
  "eeaaa"
 ]
}', 'star-battle', 'published', (unixepoch() * 1000) + 21);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('star-battle-2', 'c-wyatt', 'wyatt', 'Night Sky', 'star-battle
{
 "size": [
  6,
  6
 ],
 "areas": [
  "ffbbbc",
  "ffbbbb",
  "febeaa",
  "feeeaa",
  "feddda",
  "dddaaa"
 ]
}', 'star-battle', 'published', (unixepoch() * 1000) + 22);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('star-battle-3', 'c-wyatt', 'wyatt', 'Constellation', 'star-battle
{
 "size": [
  8,
  8
 ],
 "areas": [
  "ccaccbbb",
  "hcccgbgb",
  "hcccgggb",
  "ccccgggg",
  "cccccgdg",
  "eceeggdf",
  "ecceeedd",
  "eeeedddd"
 ]
}', 'star-battle', 'published', (unixepoch() * 1000) + 23);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('irregular-sudoku-1', 'c-wyatt', 'wyatt', 'Jigsaw', 'irregular-sudoku
{
 "size": [
  6,
  6
 ],
 "areas": [
  "eaaaaa",
  "ebbbba",
  "ebbcdd",
  "eeccdd",
  "efcccd",
  "fffffd"
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    5,
    2
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    1,
    0
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    1,
    2
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    4
   ],
   "kind": "number",
   "value": 5
  }
 ]
}', 'irregular-sudoku', 'published', (unixepoch() * 1000) + 24);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('irregular-sudoku-2', 'c-wyatt', 'wyatt', 'Crazy Paving', 'irregular-sudoku
{
 "size": [
  9,
  9
 ],
 "areas": [
  "aaaaacccf",
  "aabbabcff",
  "dagbbbcff",
  "dggbcccff",
  "ddgbbecfi",
  "ddgeeeefi",
  "dgggeeiii",
  "dgheehhii",
  "dhhhhhhii"
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    7,
    2
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    1,
    6
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    1,
    7
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    0,
    5
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    8,
    7
   ],
   "kind": "number",
   "value": 9
  },
  {
   "at": "cell",
   "cell": [
    8,
    4
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    7,
    6
   ],
   "kind": "number",
   "value": 8
  },
  {
   "at": "cell",
   "cell": [
    2,
    4
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    2,
    1
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    4,
    4
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    2,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    8,
    2
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    6,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    0,
    8
   ],
   "kind": "number",
   "value": 9
  },
  {
   "at": "cell",
   "cell": [
    1,
    5
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    4,
    7
   ],
   "kind": "number",
   "value": 3
  }
 ]
}', 'irregular-sudoku', 'published', (unixepoch() * 1000) + 25);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('akari-1', 'c-wyatt', 'wyatt', 'Lights On', 'akari
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    5,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    1,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    5
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    1,
    4
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    5
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    2,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    4
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    2,
    3
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    4
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    3,
    5
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    5,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    1
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "number",
   "value": 2
  }
 ]
}', 'akari', 'published', (unixepoch() * 1000) + 26);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('akari-2', 'c-wyatt', 'wyatt', 'Night Shift', 'akari
{
 "size": [
  8,
  8
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    7
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    7,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    1,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    6,
    7
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    1,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    6,
    5
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    1,
    6
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    6,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    2,
    6
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    7
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    5
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    7
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    4,
    0
   ],
   "kind": "block"
  },
  {
   "at": "cell",
   "cell": [
    3,
    7
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    6,
    7
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    1,
    0
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    4,
    7
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    1,
    6
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    6,
    1
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    2
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    7,
    0
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 0
  }
 ]
}', 'akari', 'published', (unixepoch() * 1000) + 27);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('shikaku-1', 'c-wyatt', 'wyatt', 'Boxes', 'shikaku
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    1,
    0
   ],
   "kind": "number",
   "value": 8
  },
  {
   "at": "cell",
   "cell": [
    0,
    5
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    5
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 8
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    5
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    4,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    5,
    4
   ],
   "kind": "number",
   "value": 2
  }
 ]
}', 'shikaku', 'published', (unixepoch() * 1000) + 28);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('shikaku-2', 'c-wyatt', 'wyatt', 'Moving Day', 'shikaku
{
 "size": [
  8,
  8
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    1,
    6
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    1,
    7
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    6
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 8
  },
  {
   "at": "cell",
   "cell": [
    7,
    0
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    4,
    3
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    4,
    6
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    4,
    7
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    4
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    7,
    2
   ],
   "kind": "number",
   "value": 8
  },
  {
   "at": "cell",
   "cell": [
    6,
    5
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    7,
    5
   ],
   "kind": "number",
   "value": 2
  }
 ]
}', 'shikaku', 'published', (unixepoch() * 1000) + 29);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-1', 'c-wyatt', 'wyatt', 'Something Sweet', 'nonogram
{
 "size": [
  5,
  5
 ],
 "picture": {
  "rows": [
   ".r.r.",
   "rrrrr",
   "rrrrr",
   ".rrr.",
   "..r.."
  ],
  "palette": {
   ".": "#e3f2f6",
   "r": "#d8443a"
  },
  "title": "Heart"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 30);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-2', 'c-wyatt', 'wyatt', 'From the Tree', 'nonogram
{
 "size": [
  10,
  10
 ],
 "picture": {
  "rows": [
   ".....b....",
   "....bgg...",
   "..rrbrrr..",
   ".rrrrrrhr.",
   "rrrrrrrrhr",
   "rrrrrrrrrr",
   "rrrrrrrrrr",
   ".rrrrrrrr.",
   ".rrrrrrrr.",
   "..rr..rr.."
  ],
  "palette": {
   ".": "#e3f2f6",
   "r": "#d8443a",
   "h": "#f29a8c",
   "b": "#6b4a2b",
   "g": "#4a9a3b"
  },
  "title": "Apple"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 31);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-3', 'c-wyatt', 'wyatt', 'Out on the Water', 'nonogram
{
 "size": [
  10,
  10
 ],
 "picture": {
  "rows": [
   "....w.....",
   "....ww....",
   "....www...",
   "....wwww..",
   "....wwwww.",
   "....m.....",
   ".bbbbbbbb.",
   "..bbbbbb..",
   "~~~~~~~~~~",
   ".~~.~~.~~."
  ],
  "palette": {
   ".": "#e3f2f6",
   "w": "#ffffff",
   "m": "#6b4a2b",
   "b": "#a0662f",
   "~": "#2f8fd8"
  },
  "title": "Sailboat"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 32);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-4', 'c-wyatt', 'wyatt', 'In the Forest', 'nonogram
{
 "size": [
  10,
  10
 ],
 "picture": {
  "rows": [
   "..rrrrrr..",
   ".rrwwrrrr.",
   "rrwwrrrwwr",
   "rrrrrrrwwr",
   "rwwrrrrrrr",
   "..cccccc..",
   "...cccc...",
   "...cccc...",
   "...cccc...",
   "..cccccc.."
  ],
  "palette": {
   ".": "#e8f1dc",
   "r": "#d8443a",
   "w": "#fff6e8",
   "c": "#e9dcc0"
  },
  "title": "Mushroom"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 33);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-5', 'c-wyatt', 'wyatt', 'Sitting Pretty', 'nonogram
{
 "size": [
  10,
  10
 ],
 "picture": {
  "rows": [
   "k...k.....",
   "kk.kk.....",
   "kkkkk.....",
   "kekek.....",
   "kkkkk...k.",
   ".kkk....k.",
   ".kkkkkkkk.",
   ".kkkkkkk..",
   ".k.k..k.k.",
   ".k.k..k.k."
  ],
  "palette": {
   ".": "#fbeed7",
   "k": "#3b3633",
   "e": "#f2c94c"
  },
  "title": "Cat"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 34);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-6', 'c-wyatt', 'wyatt', 'Tall Word', 'nonogram
{
 "size": [
  15,
  3
 ],
 "picture": {
  "rows": [
   "ppp",
   "p.p",
   "ppp",
   "p..",
   "p..",
   "...",
   "ppp",
   "p.p",
   "ppp",
   "...",
   "ppp",
   "p.p",
   "ppp",
   "p..",
   "p.."
  ],
  "palette": {
   ".": "#fdf1e4",
   "p": "#e2508f"
  },
  "title": "Pop"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 35);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-7', 'c-wyatt', 'wyatt', 'Say My Name', 'nonogram
{
 "size": [
  5,
  12
 ],
 "picture": {
  "rows": [
   "bb..bbbb.bb.",
   "b.b.b..b.b.b",
   "bb..b..b.bb.",
   "b.b.b..b.b.b",
   "bb..bbbb.bb."
  ],
  "palette": {
   ".": "#eef4fb",
   "b": "#2f6fd8"
  },
  "title": "Bob"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 36);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-8', 'c-wyatt', 'wyatt', 'First Place', 'nonogram
{
 "size": [
  10,
  7
 ],
 "picture": {
  "rows": [
   ".ttttt.",
   "t.....t",
   ".......",
   "t.ttt.t",
   "t.ttt.t",
   "t.....t",
   "ttttttt",
   ".......",
   "..ttt..",
   "..ttt.."
  ],
  "palette": {
   ".": "#eef4fb",
   "t": "#e0a422"
  },
  "title": "Trophy"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 37);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nonogram-9', 'c-wyatt', 'wyatt', 'Standing Tall', 'nonogram
{
 "size": [
  8,
  4
 ],
 "picture": {
  "rows": [
   ".ss.",
   "rrrr",
   ".rr.",
   ".rr.",
   "bbbb",
   "b..b",
   "b..b",
   "b..b"
  ],
  "palette": {
   ".": "#f3efe6",
   "s": "#e8b48a",
   "r": "#d8443a",
   "b": "#2d58a6"
  },
  "title": "Human"
 }
}', 'nonogram', 'published', (unixepoch() * 1000) + 38);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('slitherlink-1', 'c-wyatt', 'wyatt', 'First Loop', 'slitherlink
{
 "size": [
  5,
  5
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    2,
    1
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    3,
    4
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    2,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    1
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    0
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "number",
   "value": 2
  }
 ]
}', 'slitherlink', 'published', (unixepoch() * 1000) + 39);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('slitherlink-2', 'c-wyatt', 'wyatt', 'Long Way Round', 'slitherlink
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    1,
    5
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    5
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    4
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    1,
    4
   ],
   "kind": "number",
   "value": 0
  },
  {
   "at": "cell",
   "cell": [
    3,
    2
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    4,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    4,
    1
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    4
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 1
  }
 ]
}', 'slitherlink', 'published', (unixepoch() * 1000) + 40);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nurikabe-1', 'c-wyatt', 'wyatt', 'Five Islands', 'nurikabe
{
 "size": [
  5,
  5
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    0,
    2
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    0,
    4
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 5
  }
 ]
}', 'nurikabe', 'published', (unixepoch() * 1000) + 41);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('nurikabe-2', 'c-wyatt', 'wyatt', 'Archipelago', 'nurikabe
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    0,
    4
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    5
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    4,
    2
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    5,
    4
   ],
   "kind": "number",
   "value": 1
  }
 ]
}', 'nurikabe', 'published', (unixepoch() * 1000) + 42);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('panes-1', 'c-wyatt', 'wyatt', 'Four by Four', 'panes
{
 "size": [
  4,
  4
 ],
 "rules": [
  {
   "rule": "size",
   "is": 4
  },
  {
   "rule": "twins"
  },
  {
   "rule": "opposites"
  }
 ],
 "givens": [
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     2,
     2
    ]
   ],
   "kind": "opposites"
  },
  {
   "at": "border",
   "cells": [
    [
     2,
     1
    ],
    [
     3,
     1
    ]
   ],
   "kind": "twins"
  },
  {
   "at": "border",
   "cells": [
    [
     0,
     0
    ],
    [
     1,
     0
    ]
   ],
   "kind": "opposites"
  }
 ]
}', 'panes', 'published', (unixepoch() * 1000) + 43);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('panes-2', 'c-wyatt', 'wyatt', 'Compass Rose', 'panes
{
 "size": [
  5,
  5
 ],
 "rules": [
  {
   "rule": "size",
   "is": 5
  },
  {
   "rule": "twins"
  },
  {
   "rule": "compass"
  }
 ],
 "givens": [
  {
   "at": "border",
   "cells": [
    [
     3,
     3
    ],
    [
     4,
     3
    ]
   ],
   "kind": "twins"
  },
  {
   "at": "cell",
   "cell": [
    4,
    4
   ],
   "kind": "compass",
   "value": {
    "n": 0,
    "e": 0,
    "s": 0,
    "w": 4
   }
  },
  {
   "at": "cell",
   "cell": [
    2,
    1
   ],
   "kind": "compass",
   "value": {
    "n": 3,
    "e": 1,
    "s": 0,
    "w": 2
   }
  },
  {
   "at": "cell",
   "cell": [
    0,
    0
   ],
   "kind": "compass",
   "value": {
    "n": 0,
    "e": 4,
    "s": 1,
    "w": 0
   }
  }
 ]
}', 'panes', 'published', (unixepoch() * 1000) + 44);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('sudoku-1', 'c-wyatt', 'wyatt', 'Warm-up', 'sudoku
{
 "size": [
  4,
  4
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    3,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    2,
    0
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    2
   ],
   "kind": "number",
   "value": 1
  }
 ]
}', 'sudoku', 'published', (unixepoch() * 1000) + 45);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('sudoku-2', 'c-wyatt', 'wyatt', 'Six by Six', 'sudoku
{
 "size": [
  6,
  6
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    2,
    4
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    2,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    1,
    2
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    0,
    3
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    5,
    0
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 3
  }
 ]
}', 'sudoku', 'published', (unixepoch() * 1000) + 46);
INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES ('sudoku-3', 'c-wyatt', 'wyatt', 'Classic', 'sudoku
{
 "size": [
  9,
  9
 ],
 "givens": [
  {
   "at": "cell",
   "cell": [
    7,
    2
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    7,
    6
   ],
   "kind": "number",
   "value": 9
  },
  {
   "at": "cell",
   "cell": [
    5,
    3
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    1,
    3
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    2,
    4
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    0,
    7
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    8,
    2
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    0,
    5
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    7,
    5
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    3,
    0
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    5,
    1
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    3,
    7
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    5,
    2
   ],
   "kind": "number",
   "value": 7
  },
  {
   "at": "cell",
   "cell": [
    0,
    1
   ],
   "kind": "number",
   "value": 4
  },
  {
   "at": "cell",
   "cell": [
    7,
    4
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    8,
    1
   ],
   "kind": "number",
   "value": 6
  },
  {
   "at": "cell",
   "cell": [
    1,
    5
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    1,
    6
   ],
   "kind": "number",
   "value": 3
  },
  {
   "at": "cell",
   "cell": [
    3,
    8
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    4,
    7
   ],
   "kind": "number",
   "value": 9
  },
  {
   "at": "cell",
   "cell": [
    6,
    5
   ],
   "kind": "number",
   "value": 8
  },
  {
   "at": "cell",
   "cell": [
    8,
    7
   ],
   "kind": "number",
   "value": 5
  },
  {
   "at": "cell",
   "cell": [
    5,
    8
   ],
   "kind": "number",
   "value": 2
  },
  {
   "at": "cell",
   "cell": [
    2,
    7
   ],
   "kind": "number",
   "value": 1
  },
  {
   "at": "cell",
   "cell": [
    6,
    1
   ],
   "kind": "number",
   "value": 7
  }
 ]
}', 'sudoku', 'published', (unixepoch() * 1000) + 47);
INSERT OR IGNORE INTO featured (game_id, position, featured_by) VALUES ('simple-loop-5', 0, 'wyatt'), ('panes-1', 1, 'wyatt'), ('sudoku-1', 2, 'wyatt'), ('nonogram-2', 3, 'wyatt');
