"""Write seed/dev.sql: local development data for the social site.

    python3 seed/make.py && npm run db:seed

Wyatt (no password, so this account can't sign in), his personal collection, and every grid
puzzle from the current site (../src/games), as sketches. A few go on the Featured shelf.
"""
import json
from pathlib import Path

GAMES = Path(__file__).resolve().parents[2] / "src" / "games"
GENRES = {"round-the-bend": "river", "picture-squares": "nonogram", "slitherlink": "slitherlink",
          "nurikabe": "nurikabe", "panes": "panes", "sudoku": "sudoku"}
FEATURED = ["river-5", "panes-1", "sudoku-1", "nonogram-2"]

q = lambda s: "'" + s.replace("'", "''") + "'"
out = [
    "-- Generated by seed/make.py: Wyatt, his collection, and the current site's grid puzzles as sketches.",
    "INSERT OR IGNORE INTO creators (id, name, email, handle) VALUES ('wyatt', 'Wyatt', 'wyatt@example.invalid', 'wyatt');",
    "INSERT OR IGNORE INTO collections (id, slug, title, description, personal_of) VALUES "
    "('c-wyatt', 'wyatt', 'Wyatt''s Games', 'Puzzles Wyatt drew.', 'wyatt');",
    "INSERT OR IGNORE INTO memberships (collection_id, creator_id, role) VALUES ('c-wyatt', 'wyatt', 'owner');",
]
stamp = 0
for folder, genre in GENRES.items():
    for f in sorted((GAMES / folder).glob("*.json"), key=lambda p: int(p.stem)):
        d = json.loads(f.read_text())
        body = {k: v for k, v in d["grid"].items() if k not in ("genre", "source")}
        sketch = f"{genre}\n" + json.dumps(body, indent=1)
        gid, stamp = f"{genre}-{f.stem}", stamp + 1
        out.append("INSERT OR IGNORE INTO games (id, collection_id, author_id, title, sketch, kind, state, published_at) VALUES "
                   f"({q(gid)}, 'c-wyatt', 'wyatt', {q(d['name'])}, {q(sketch)}, {q(genre)}, 'published', (unixepoch() * 1000) + {stamp});")
out.append("INSERT OR IGNORE INTO featured (game_id, position, featured_by) VALUES "
           + ", ".join(f"({q(g)}, {i}, 'wyatt')" for i, g in enumerate(FEATURED)) + ";")
(Path(__file__).parent / "dev.sql").write_text("\n".join(out) + "\n")
print(f"{stamp} games")
