// The AI creators' difficulty sheet: for each persona, the easiest and the hardest puzzle in a
// backfill batch (puzzles/ai/backfill.ts), by scored difficulty, each with its picture, date, the
// day's target, the score and the rule load, so the range can be checked by eye. Writes
// docs/ai-creators-difficulty.html. The picture code has extensionless imports, so run it with tsx:
//
//   npx tsx puzzles/ai/difficulty-sheet.ts [--file puzzles/ai/out/backfill.json]
import { readFileSync, writeFileSync } from "node:fs";
import { makePuzzle } from "../../src/engine/puzzle.ts";
import type { GridSpec } from "../../src/engine/types.ts";
import { pictureSvg } from "../../src/game-types/grid/picture.ts";
import { guides } from "../../src/guides/guides.ts";
import { PERSONAS, type Persona } from "../../app/app/ai/personas.ts";
import type { BackfillFile, BackfillRecord } from "./backfill.ts";

const argv = process.argv.slice(2);
const arg = (k: string, d: string) => { const i = argv.indexOf(`--${k}`); return i >= 0 ? argv[i + 1] : d; };
const file = arg("file", "puzzles/ai/out/backfill.json");
const out = arg("out", "docs/ai-creators-difficulty.html");
const batch = JSON.parse(readFileSync(file, "utf8")) as BackfillFile;

const esc = (t: string) => t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const css = readFileSync(new URL("../../src/styles/global.css", import.meta.url), "utf8");
const root = css.slice(css.indexOf(":root {"), css.indexOf("}", css.indexOf(":root {")) + 1);
const gridCss = readFileSync(new URL("../../src/game-types/grid/styles.css", import.meta.url), "utf8");

const specOf = (r: BackfillRecord): GridSpec => ({ ...JSON.parse(r.sketch.slice(r.sketch.indexOf("\n") + 1)), genre: r.genre });
const scheme = (p: Persona) => {
  const d = p.difficulty;
  switch (d.kind) {
    case "weekday": return `weekday: ${Object.entries(d.by).filter(([w]) => p.schedule.days === "prime-dates" || p.schedule.days.includes(w as never)).map(([w, v]) => `${w} ${v}`).join(", ")}`;
    case "steady": return `steady ${d.level} ± ${d.wobble / 2}`;
    case "season": return `season: ${Object.entries(d.by).map(([s, v]) => `${s} ${v}`).join(", ")}`;
    case "school-year": return `school year ${d.low}–${d.high}, summer ${d.summer}`;
    default: return `${d.kind} ${d.low}–${d.high}`;
  }
};
const loadOf = (r: BackfillRecord) => r.score.measures.ruleLoad ?? 1;
const kindsOf = (r: BackfillRecord) => r.score.notes.find((n) => n.startsWith("rule load"))?.replace(/^rule load [\d.]+: /, "") ?? "";

function card(r: BackfillRecord, label: string) {
  let pic = "";
  try { pic = pictureSvg(makePuzzle(specOf(r)), null, `${r.genre} ${r.date}`); } catch (e) { pic = `<p class="err">no picture: ${esc(String(e))}</p>`; }
  const g = guides[r.genre as keyof typeof guides];
  const what = [g?.name ?? r.genre, r.mix && `mix ${r.mix}`, r.rules && `rules ${r.rules}`, r.moves && `moves ${r.moves}`].filter(Boolean).join(" · ");
  const load = loadOf(r);
  return `<figure><figcaption><b>${label}</b> ${esc(r.date)} (${r.weekday})</figcaption>
<div class="grid-game pic" style="--paper-ink:${g?.ink ?? "#26398f"}">${pic}</div>
<p class="what">${esc(what)}, ${r.size.join(" × ")}</p>
<dl><dt>target</dt><dd>${r.target.toFixed(2)}</dd><dt>scored</dt><dd>${r.score.difficulty.toFixed(2)}</dd>
<dt>rule load</dt><dd class="${load >= 3 ? "hi" : load > 1 ? "mid" : ""}">${+load.toFixed(2)}${kindsOf(r) ? ` <span>(${esc(kindsOf(r))})</span>` : ""}</dd>
<dt>logic</dt><dd>${(r.score.measures.logic ?? r.score.difficulty).toFixed(2)}</dd></dl></figure>`;
}

const rows = PERSONAS.map((p) => {
  const mine = batch.posts.filter((r) => r.persona === p.handle);
  if (!mine.length) return `<section><h2>${esc(p.name)} <span>@${p.handle}</span></h2><p>No posts in this batch.</p></section>`;
  const by = [...mine].sort((a, b) => a.score.difficulty - b.score.difficulty || a.target - b.target);
  const easiest = by[0], hardest = by.at(-1)!;
  const targets = mine.map((r) => r.target), scores = mine.map((r) => r.score.difficulty), loads = mine.map(loadOf);
  const range = (xs: number[]) => `${Math.min(...xs).toFixed(2)}–${Math.max(...xs).toFixed(2)}`;
  return `<section><h2>${esc(p.name)} <span>@${p.handle}</span></h2>
<p class="meta">${mine.length} posts · ${esc(scheme(p))} · targets ${range(targets)} · scored ${range(scores)} · rule load ${range(loads)}</p>
<div class="pair">${card(easiest, "Easiest")}${card(hardest, "Hardest")}</div></section>`;
});

const total = batch.posts.length;
writeFileSync(out, `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>AI creators' difficulty</title>
<!-- Generated by puzzles/ai/difficulty-sheet.ts from ${esc(file)} (${total} posts, ${esc(batch.updated)}). Don't edit by hand. -->
<style>
  ${root}
  ${gridCss}
  body { margin: 0; padding: 16px; font: 14px/1.4 Nunito, system-ui, sans-serif; background: var(--bg, #fbfbf9); color: var(--ink, #222); }
  h1 { margin: 0 0 4px; font-size: 20px; }
  .lede { margin: 0 0 16px; color: var(--muted, #666); max-width: 80ch; }
  main { display: grid; grid-template-columns: repeat(auto-fill, minmax(560px, 1fr)); gap: 16px; }
  section { border: 1px solid var(--line, #ddd); border-radius: 8px; padding: 12px; background: var(--panel, #fff); }
  h2 { margin: 0; font-size: 16px; } h2 span { font-weight: 400; color: var(--muted, #666); }
  .meta { margin: 2px 0 10px; font-size: 12px; color: var(--muted, #666); }
  .pair { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  figure { margin: 0; }
  figcaption { font-size: 13px; margin-bottom: 6px; }
  .pic { display: block; } .pic svg { width: 100%; max-height: 240px; height: auto; display: block; }
  .what { margin: 6px 0 2px; font-size: 12px; }
  dl { display: grid; grid-template-columns: auto 1fr; gap: 0 8px; margin: 0; font-size: 12px; }
  dt { color: var(--muted, #666); } dd { margin: 0; font-variant-numeric: tabular-nums; }
  dd span { color: var(--muted, #666); }
  dd.mid { color: #b06a00; } dd.hi { color: #c0392b; font-weight: 700; }
  .err { color: #c0392b; font-size: 12px; }
  @media (max-width: 640px) { main { grid-template-columns: 1fr; } .pair { grid-template-columns: 1fr; } }
</style></head>
<body><h1>AI creators: the easiest and hardest puzzle each</h1>
<p class="lede">From ${esc(file)}: ${total} posts over the backfill range, placeholder words. Target is the day's difficulty from the persona's scheme; scored is the proxy scorer's estimate (puzzles/ai/score.ts), which joins the logic (size, sparsity, search) and the rule load (rules or symbol kinds to hold in mind; 1 is a plain genre, 4 or more puts any board at 0.7 or above).</p>
<main>${rows.join("\n")}</main>
</body></html>
`);
console.log(`wrote ${out} (${PERSONAS.length} creators, ${total} posts)`);
