// A tutor's curriculum on one page: each week a row of its five posts (Monday to Friday), with the
// picture, the title, the day's step and what the checks found (the trap's rival, the change from
// the day before). For checking a backfill by eye. Writes puzzles/ai/out/slate-curriculum.html (gitignored: it is large). The picture
// code has extensionless imports, so run it with tsx:
//
//   npx tsx puzzles/ai/lesson-sheet.ts [--file puzzles/ai/out/slate.json] [--out <file>] [--answers]
import { readFileSync, writeFileSync } from "node:fs";
import { makePuzzle } from "../../src/engine/puzzle.ts";
import { solve } from "../../src/engine/solve.ts";
import type { GridSpec } from "../../src/engine/types.ts";
import { pictureSvg } from "../../src/game-types/grid/picture.ts";
import { guides } from "../../src/guides/guides.ts";
import { PERSONAS } from "../../app/app/ai/personas.ts";
import { lessonFor } from "../../app/app/ai/schedule.ts";
import type { BackfillFile, BackfillRecord } from "./backfill.ts";

const argv = process.argv.slice(2);
const arg = (k: string, d: string) => { const i = argv.indexOf(`--${k}`); return i >= 0 ? argv[i + 1] : d; };
const file = arg("file", "puzzles/ai/out/slate.json"), out = arg("out", "puzzles/ai/out/slate-curriculum.html"), handle = arg("persona", "slate");
const answers = argv.includes("--answers");
const p = PERSONAS.find((x) => x.handle === handle)!;
const batch = JSON.parse(readFileSync(file, "utf8")) as BackfillFile;
const mine = batch.posts.filter((r) => r.persona === handle);

const esc = (t: string) => t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const css = readFileSync(new URL("../../src/styles/global.css", import.meta.url), "utf8");
const root = css.slice(css.indexOf(":root {"), css.indexOf("}", css.indexOf(":root {")) + 1);
const gridCss = readFileSync(new URL("../../src/game-types/grid/styles.css", import.meta.url), "utf8");
const specOf = (r: BackfillRecord): GridSpec => ({ ...JSON.parse(r.sketch.slice(r.sketch.indexOf("\n") + 1)), genre: r.genre as GridSpec["genre"] });
const STEP: Record<string, string> = { introduce: "introduce", contrast: "contrast", "second-contrast": "contrast again", trap: "trap", combine: "combine", review: "review" };

async function card(r: BackfillRecord) {
  const lesson = lessonFor(p, { date: r.date, weekday: r.weekday as never })!;
  let pic = "";
  try { const pz = makePuzzle(specOf(r)); pic = pictureSvg(pz, answers ? (await solve(pz, 1))[0] : null, r.title); } catch (e) { pic = `<p class="err">${esc(String(e))}</p>`; }
  const note = r.score.notes.find((n) => n.startsWith("trap:")) ?? r.score.notes.find((n) => n.startsWith("one change")) ?? r.score.notes.find((n) => n.includes("worked:")) ?? "";
  return `<figure><figcaption><b>${esc(r.placeholder ? `${lesson.subject.name} · ${STEP[lesson.step]}` : r.title)}</b><span>${esc(r.date)} · ${STEP[lesson.step]}${lesson.focus !== lesson.subject ? ` (${esc(lesson.focus.name)})` : ""}</span></figcaption>
<div class="grid-game pic" style="--paper-ink:${guides[r.genre as keyof typeof guides]?.ink ?? "#26398f"}">${pic}</div>
${r.placeholder ? "" : `<p class="desc">${esc(r.description)}</p>`}<p class="note">${esc(note.replace(/^one change from the day before's board /, "changed: "))}</p></figure>`;
}

const weeks = new Map<number, BackfillRecord[]>();
for (const r of mine) { const l = lessonFor(p, { date: r.date, weekday: r.weekday as never })!; weeks.set(l.week, [...(weeks.get(l.week) ?? []), r]); }
const rows: string[] = [];
for (const [w, posts] of [...weeks].sort((a, b) => a[0] - b[0])) {
  const s = p.curriculum![((w % p.curriculum!.length) + p.curriculum!.length) % p.curriculum!.length];
  rows.push(`<section><h2>Week ${w + 1}: ${esc(s.name)} <span>${esc(s.reading ?? (s.review ? `review: ${s.review.join(", ")}` : guides[s.genre as keyof typeof guides]?.name ?? s.genre))}</span></h2><div class="week">${(await Promise.all(posts.map(card))).join("")}</div></section>`);
}

writeFileSync(out, `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Slate's curriculum</title>
<!-- Generated by puzzles/ai/lesson-sheet.ts from ${esc(file)} (${mine.length} posts). Don't edit by hand. -->
<style>
  ${root}
  ${gridCss}
  body { margin: 0; padding: 16px; font: 14px/1.4 Nunito, system-ui, sans-serif; background: var(--bg, #fbfbf9); color: var(--ink, #222); }
  h1 { margin: 0 0 4px; font-size: 20px; } .lede { margin: 0 0 16px; color: var(--muted, #666); }
  section { border-top: 1px solid var(--line, #ddd); padding: 10px 0; }
  h2 { margin: 0 0 8px; font-size: 15px; } h2 span { font-weight: 400; color: var(--muted, #666); }
  .week { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 12px; }
  figure { margin: 0; } figcaption b { display: block; font-size: 13px; } figcaption span { font-size: 11px; color: var(--muted, #666); }
  .pic svg { width: 100%; max-height: 170px; height: auto; display: block; margin-top: 4px; }
  .desc { margin: 4px 0 0; font-size: 12px; } .note { margin: 2px 0 0; font-size: 11px; color: var(--muted, #666); }
  .err { color: #c0392b; font-size: 12px; }
  @media (max-width: 800px) { .week { grid-template-columns: repeat(2, minmax(0, 1fr)); } }
</style></head>
<body><h1>${esc(p.name)}'s curriculum</h1>
<p class="lede">${mine.length} posts, ${esc(p.curriculumStart!)} to ${esc(mine.at(-1)?.date ?? "")}, from ${esc(file)}. Each week: introduce, contrast, contrast again, trap, then review or combine.</p>
${rows.join("\n")}
</body></html>
`);
console.log(`wrote ${out} (${weeks.size} weeks, ${mine.length} posts)`);
