// The AI creators' contact sheet: every persona's icon at 24, 40 and 96 px on the light page and the
// dark one, with its name, handle and the start of its bio. Writes docs/ai-creators-sheet.html.
//
//   node puzzles/ai/sheet.ts
import { readFileSync, writeFileSync } from "node:fs";
import { PERSONAS } from "../../app/app/ai/personas.ts";
import { personaIcon } from "../../app/app/ai/icons.ts";

const esc = (t: string) => t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
// the site's colour tokens, light and dark, straight from its stylesheet
const css = readFileSync(new URL("../../src/styles/global.css", import.meta.url), "utf8");
const tokens = (block: string) => [...block.matchAll(/(--(?:bg|panel|ink|muted|line|paper|paper-ink|paper-red|sumi|shell|wash-[a-z]+)):\s*([^;]+);/g)].map(([, k, v]) => `${k}: ${v};`).join(" ");
const light = tokens(css.slice(css.indexOf(":root {"), css.indexOf("}", css.indexOf(":root {"))));
const darkAt = css.indexOf(':root[data-theme="dark"]');
const dark = tokens(css.slice(darkAt, css.indexOf("}", darkAt)));

const card = (p: (typeof PERSONAS)[number]) => {
  const icon = personaIcon(p.handle)!;
  const sizes = [24, 40, 96].map((n) => `<span class="icon" style="width:${n}px;height:${n}px">${icon}</span>`).join("");
  const kinds = [...new Set(p.genres.map((g) => g.genre))].join(", ");
  return `<article><div class="sizes">${sizes}</div><div class="who"><b>${esc(p.name)}</b> <span class="handle">@${p.handle}</span> <span class="ai">AI</span>
<p>${esc(p.bio.length > 150 ? `${p.bio.slice(0, 147).replace(/\s\S*$/, "")} …` : p.bio)}</p><p class="kinds">${kinds}</p></div></article>`;
};
const half = (theme: string) => `<section class="${theme}"><h2>${theme === "light" ? "Light" : "Dark"}</h2>${PERSONAS.map(card).join("\n")}</section>`;

writeFileSync(new URL("../../docs/ai-creators-sheet.html", import.meta.url), `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>AI creators' icons</title>
<!-- Generated by puzzles/ai/sheet.ts from app/app/ai/personas.ts and icons.ts. Don't edit by hand. -->
<style>
  body { margin: 0; font: 14px/1.4 Nunito, system-ui, sans-serif; background: #888; }
  h1 { margin: 0; padding: 16px 20px; font-size: 18px; background: #fbfbf9; color: #26398f; }
  main { display: grid; grid-template-columns: 1fr 1fr; }
  section { padding: 12px 20px 20px; background: var(--bg); color: var(--ink); }
  section.light { ${light} }
  section.dark { ${light} ${dark} }
  h2 { margin: 4px 0 8px; font-size: 13px; text-transform: uppercase; letter-spacing: .08em; color: var(--muted); }
  article { display: grid; grid-template-columns: 190px 1fr; gap: 14px; align-items: center; padding: 10px 0; border-top: 1px solid var(--line); }
  .sizes { display: flex; align-items: center; gap: 14px; }
  .icon { display: inline-block; flex: none; }
  .icon svg { display: block; width: 100%; height: 100%; }
  .handle { color: var(--muted); }
  .ai { display: inline-block; padding: 1px 5px; border: 1.5px solid currentColor; border-radius: 4px; font-size: 10.5px; font-weight: 800; letter-spacing: .08em; }
  p { margin: 4px 0 0; max-width: 46ch; }
  .kinds { font-size: 12px; color: var(--muted); }
  @media (max-width: 900px) { main { grid-template-columns: 1fr; } }
</style></head>
<body><h1>inkit's AI creators: ${PERSONAS.length} icons at 24, 40 and 96 px</h1>
<main>${half("light")}${half("dark")}</main>
</body></html>
`);
console.log(`wrote docs/ai-creators-sheet.html (${PERSONAS.length} creators)`);
