// Pictures for nonograms made by puzzles/grid/generate.ts (and so by the AI creators' weekly batch):
// small things from a house and a garden, one letter per square ("." is empty), with the colours
// the picture shows once it's solved. Only pictures whose clues allow nothing else are used; the
// generator checks each one, so a picture here that turns out ambiguous is just skipped.
export interface Picture { title: string; rows: string[]; palette: Record<string, string> }

const SKY = "#eef4fb", CREAM = "#f6efe2", LEAF = "#e8f1dc";

export const PICTURES: Picture[] = [
  // ---- 5 × 5 ----
  { title: "Crescent moon", palette: { ".": SKY, m: "#e0a422" }, rows: [
    ".mm..",
    "mm...",
    "mm...",
    "mm...",
    ".mm..",
  ] },
  { title: "Fir tree", palette: { ".": SKY, g: "#4a9a3b", b: "#6b4a2b" }, rows: [
    "..g..",
    ".ggg.",
    "ggggg",
    "..b..",
    ".bbb.",
  ] },
  { title: "Bell", palette: { ".": CREAM, y: "#e0a422", b: "#6b4a2b" }, rows: [
    "..b..",
    ".yyy.",
    ".yyy.",
    "yyyyy",
    "..y..",
  ] },
  { title: "Fish", palette: { ".": SKY, o: "#f29a38" }, rows: [
    ".....",
    ".oo.o",
    "oooo.",
    ".oo.o",
    ".....",
  ] },
  { title: "Mushroom", palette: { ".": LEAF, r: "#d8443a", c: "#e9dcc0" }, rows: [
    ".rrr.",
    "rrrrr",
    "..c..",
    "..c..",
    ".ccc.",
  ] },
  { title: "Kite", palette: { ".": SKY, k: "#e2508f", t: "#26398f" }, rows: [
    "..k..",
    ".kkk.",
    "..k..",
    "..t..",
    "..tt.",
  ] },

  // ---- 8 × 8 ----
  { title: "Pear", palette: { ".": CREAM, y: "#c9c23a", b: "#6b4a2b", g: "#4a9a3b" }, rows: [
    "....b...",
    "....bgg.",
    "...yy...",
    "..yyyy..",
    "..yyyy..",
    ".yyyyyy.",
    ".yyyyyy.",
    "..yyyy..",
  ] },
  { title: "Teacup", palette: { ".": CREAM, t: "#3f6fb0", s: "#b9b2a6" }, rows: [
    "..s.....",
    "...s....",
    "..s.....",
    "tttttt..",
    "tttttttt",
    "tttttt.t",
    ".tttttt.",
    "..tttt..",
  ] },
  { title: "Snail", palette: { ".": LEAF, s: "#a0662f", b: "#c9a27a" }, rows: [
    "........",
    "..ssss..",
    ".ss..ss.",
    ".s.ss.s.",
    ".s.s..s.",
    ".ss..ss.",
    "bbsssbbb",
    "bbbbbb..",
  ] },
  { title: "Acorn", palette: { ".": LEAF, c: "#6b4a2b", a: "#c98a3a" }, rows: [
    "...c....",
    "..cccc..",
    ".cccccc.",
    ".aaaaaa.",
    ".aaaaaa.",
    "..aaaa..",
    "..aaaa..",
    "...aa...",
  ] },
  { title: "Sailing boat", palette: { ".": SKY, w: "#b9b2a6", h: "#a0662f", s: "#2f8fd8" }, rows: [
    "...w....",
    "...ww...",
    "...www..",
    "...wwww.",
    "...h....",
    "hhhhhhhh",
    ".hhhhhh.",
    "ssssssss",
  ] },
  { title: "House", palette: { ".": SKY, r: "#d8443a", w: "#e9dcc0", d: "#6b4a2b" }, rows: [
    "...rr...",
    "..rrrr..",
    ".rrrrrr.",
    "rrrrrrrr",
    ".ww..ww.",
    ".ww..ww.",
    ".wwddww.",
    ".wwddww.",
  ] },
  { title: "Cherries", palette: { ".": CREAM, r: "#d8443a", g: "#4a9a3b" }, rows: [
    "....ggg.",
    "...g..g.",
    "..g...g.",
    "..g...g.",
    ".rrr.rrr",
    "rrrrrrrr",
    "rrrrrrrr",
    ".rrr.rrr",
  ] },
  { title: "Umbrella", palette: { ".": SKY, u: "#a77bd6", h: "#6b4a2b" }, rows: [
    "...uu...",
    ".uuuuuu.",
    "uuuuuuuu",
    "u.u.uu.u",
    "...h....",
    "...h....",
    "...h.h..",
    "....h...",
  ] },

  // ---- 10 × 10 ----
  { title: "Watering can", palette: { ".": LEAF, c: "#3f6fb0" }, rows: [
    "..........",
    "...ccc....",
    "..c...c...",
    "cccccccc..",
    "cccccccc.c",
    "ccccccccc.",
    "cccccccc..",
    "cccccccc..",
    "cccccccc..",
    "..........",
  ] },
  { title: "Bee", palette: { ".": SKY, y: "#f2c94c", k: "#3b3633", w: "#cfe3f2" }, rows: [
    "..ww..ww..",
    ".wwww.www.",
    "..ww..ww..",
    "...yyyy...",
    "..ykkkky..",
    ".yyyyyyyy.",
    ".kkkkkkkk.",
    ".yyyyyyyy.",
    "..kkkkkk..",
    "....kk....",
  ] },
  { title: "Candle", palette: { ".": "#2b2a33", f: "#f2c94c", w: "#efece4", h: "#a0662f" }, rows: [
    "....f.....",
    "...fff....",
    "...fff....",
    "....f.....",
    "...www....",
    "...www....",
    "...www....",
    "...www....",
    ".hhhhhhh..",
    "..hhhhh.hh",
  ] },
  { title: "Moth", palette: { ".": "#2b2a33", m: "#c9a27a", b: "#6b4a2b" }, rows: [
    "...b..b...",
    "....bb....",
    "mm..bb..mm",
    "mmm.bb.mmm",
    "mmmmbbmmmm",
    "mmmmbbmmmm",
    ".mmmbbmmm.",
    "..mmbbmm..",
    "...m..m...",
    "..........",
  ] },
  { title: "Apple core", palette: { ".": CREAM, r: "#d8443a", c: "#f3e6c4", b: "#6b4a2b" }, rows: [
    "....b.....",
    "..rrbrr...",
    ".rrrrrrr..",
    "..cccccc..",
    "...cccc...",
    "...c.cc...",
    "...cccc...",
    "..cccccc..",
    ".rrrrrrr..",
    "..rrrrr...",
  ] },
  { title: "Clover", palette: { ".": LEAF, g: "#4a9a3b" }, rows: [
    "...gg.gg..",
    "..gggggggg",
    "..gggggggg",
    "...gggggg.",
    "gggggggg..",
    "ggggggggg.",
    ".gggg.ggg.",
    ".......gg.",
    "......gg..",
    ".....gg...",
  ] },
  { title: "Teapot", palette: { ".": CREAM, t: "#3f6fb0", k: "#26398f" }, rows: [
    "....kk....",
    "...tttt...",
    ".tttttttt.",
    "t.tttttttt",
    "t.ttttttt.",
    "t.tttttttt",
    ".ttttttt.t",
    "..tttttt.t",
    "...tttt...",
    "..........",
  ] },
  { title: "Owl", palette: { ".": "#2b2a33", o: "#a0662f", w: "#efece4", y: "#f2c94c" }, rows: [
    ".o......o.",
    ".oo....oo.",
    ".oooooooo.",
    "oww.oo.wwo",
    "owwyoowywo",
    "oooo..oooo",
    ".oooooooo.",
    ".oo.oo.oo.",
    "..oooooo..",
    "..y....y..",
  ] },
  { title: "Rocket", palette: { ".": "#2b2a33", w: "#efece4", r: "#d8443a", f: "#f29a38" }, rows: [
    "....rr....",
    "...wwww...",
    "...w..w...",
    "...wwww...",
    "...wwww...",
    "..rwwwwr..",
    ".rrwwwwrr.",
    ".r..ff..r.",
    "....ff....",
    ".....f....",
  ] },
];
